# -*- coding: utf-8 -*-
"""metodo haversine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NK_Jh6UY_Gx-4Cd0lh7untzC0YHMcKPL
"""

import math

def haversine(coord1, coord2):
    """
    Calcula la distancia entre dos puntos en la Tierra usando la fórmula de Haversine.

    Parámetros:
    coord1 -- (latitud, longitud) en grados decimales
    coord2 -- (latitud, longitud) en grados decimales

    Retorna:
    Distancia en metros y kilómetros
    """

    # Radio de la Tierra en metros
    R = 6371000

    # Extraer latitudes y longitudes
    lat1, lon1 = coord1
    lat2, lon2 = coord2

    # Convertir grados a radianes
    phi_1 = math.radians(lat1)
    phi_2 = math.radians(lat2)

    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)

    # Fórmula de Haversine
    a = math.sin(delta_phi / 2.0) ** 2 + math.cos(phi_1) * math.cos(phi_2) * math.sin(delta_lambda / 2.0) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Distancia en metros y kilómetros
    meters = round(R * c, 3)
    km = round(meters / 1000, 3)

    return meters, km

# Coordenadas del SGC y REDNE
coord_sgc = (6.749, -73.065)
coord_redne = (6.81, -73.27)

# Calcular la distancia
dist_m, dist_km = haversine(coord_sgc, coord_redne)

print(f"Distancia: {dist_m} m")
print(f"Distancia: {dist_km} km")