# -*- coding: utf-8 -*-
"""regresionparacoeficientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_cSYBOUuyU_EZaotXZ9nd5ahxB9OiKE
"""

import numpy as np
from scipy.stats import linregress

# Valores de amplitud (hipotéticos) y magnitud
amplitudes = np.array([5993, 59127, 46404, 19938, 123147])
magnitudes = np.array([3.2, 4.2, 4.5, 3.9, 4.4])

# Transformación logarítmica
X = np.log10(amplitudes)

# Ajuste por regresión lineal
slope, intercept, r_value, p_value, std_err = linregress(X, magnitudes)

print(f"Coeficiente a (slope): {slope:.2f}")
print(f"Coeficiente b (intercept): {intercept:.2f}")
print(f"Coeficiente de determinación R²: {r_value**2:.2f}")